/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.Timer;

/**
 *
 * @author Przemyslaw Swiderski, Adam Gorazda
 */
public class GUI extends javax.swing.JFrame
{

    private Kalendarz kalendarz;

    /**
     * Creates new form GUI
     */
    public GUI()
    {
        kalendarz = new Kalendarz();

        t = new Timer(1000, new ActionListener()
        {
            public void actionPerformed(ActionEvent e)
            {
                kalendarz.currentTime = Calendar.getInstance();
                //zegarText.setText(String.valueOf(Calendar.getInstance().get(Calendar.SECOND)));
                zegarText.setText(kalendarz.getBiezacyCzas());
                kalendarz.porownajCzas();
            }
        });
        t.start();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        bazadanychframe = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        zdarzenia = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        serializujButton = new javax.swing.JButton();
        deserializujButton = new javax.swing.JButton();
        zapiszCSVButton = new javax.swing.JButton();
        wczytajCSVButton = new javax.swing.JButton();
        czyCzysc = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        takButton = new javax.swing.JButton();
        nieButton = new javax.swing.JButton();
        oprogramieframe = new javax.swing.JFrame();
        jPanel6 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        kasujDialog = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        kasujPole = new javax.swing.JTextField();
        kasujButton = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Miesiac = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Rok = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Dni = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        dni = new javax.swing.JList();
        warning = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        testujButton = new javax.swing.JButton();
        ustawPrzypButton = new javax.swing.JButton();
        nastawText = new javax.swing.JTextField();
        zegarText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Zamknij = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        SpinnerModel model =
        new SpinnerNumberModel(12, //initial value
            0, //min
            23, //max
            1);                //step
        godzina = new javax.swing.JSpinner(model);
        Zdarzenia = new javax.swing.JPanel();
        dodajZdarzenie = new javax.swing.JButton();
        wyswietl = new javax.swing.JButton();
        czysc = new javax.swing.JButton();
        kasujbutton = new javax.swing.JButton();
        nazwazdarzenia = new javax.swing.JPanel();
        glownyPanel = new javax.swing.JScrollPane();
        nazwaZdarzenia = new javax.swing.JTextPane();
        minuty = new javax.swing.JPanel();
        minutySlider = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        miejscePanel = new javax.swing.JPanel();
        miejsceTextArea = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        bazadanychframe.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        bazadanychframe.setTitle("Zdarzenia");
        bazadanychframe.setMinimumSize(new java.awt.Dimension(600, 600));

        zdarzenia.setAutoCreateRowSorter(true);
        zdarzenia.setModel(new BdHibernate().getTableModel());
        jScrollPane1.setViewportView(zdarzenia);

        jButton4.setText("ZAMKNIJ");
        jButton4.addActionListener(formListener);

        jButton3.setText("Kasuj wybrane");
        jButton3.addActionListener(formListener);

        serializujButton.setText("SerializujXML");
        serializujButton.addActionListener(formListener);

        deserializujButton.setText("DeserializujXML");
        deserializujButton.addActionListener(formListener);

        zapiszCSVButton.setText("Zapisz do CSV");
        zapiszCSVButton.addActionListener(formListener);

        wczytajCSVButton.setText("Wczytaj z pliku CSV");
        wczytajCSVButton.addActionListener(formListener);

        javax.swing.GroupLayout bazadanychframeLayout = new javax.swing.GroupLayout(bazadanychframe.getContentPane());
        bazadanychframe.getContentPane().setLayout(bazadanychframeLayout);
        bazadanychframeLayout.setHorizontalGroup(
            bazadanychframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bazadanychframeLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bazadanychframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wczytajCSVButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deserializujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zapiszCSVButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(serializujButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        bazadanychframeLayout.setVerticalGroup(
            bazadanychframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bazadanychframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serializujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deserializujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(zapiszCSVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(wczytajCSVButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        czyCzysc.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        czyCzysc.setMinimumSize(new java.awt.Dimension(400, 300));
        czyCzysc.setType(java.awt.Window.Type.POPUP);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Czy na pewno chcesz wyczyscic?");

        takButton.setText("TAK");
        takButton.addActionListener(formListener);

        nieButton.setText("NIE");
        nieButton.addActionListener(formListener);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(takButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nieButton, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(takButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout czyCzyscLayout = new javax.swing.GroupLayout(czyCzysc.getContentPane());
        czyCzysc.getContentPane().setLayout(czyCzyscLayout);
        czyCzyscLayout.setHorizontalGroup(
            czyCzyscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(czyCzyscLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        czyCzyscLayout.setVerticalGroup(
            czyCzyscLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(czyCzyscLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        oprogramieframe.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        oprogramieframe.setMinimumSize(new java.awt.Dimension(300, 400));

        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));

        jToggleButton1.setText("ZAMKNIJ");
        jToggleButton1.addActionListener(formListener);

        jTextPane1.setEditable(false);
        jTextPane1.setText("Projekt Java - Kalendarz\n\nProgram umożliwia zapisywanie zdarzeń i odczytywanie do i z Bazy Danych.\nZdarzenia można również serializować i deserializować.\nMożliwe jest również ustawienie czasu w którym nastąpi alarm dźwiękowy.\n\nAutorzy: \nPrzemysław Świderski\nAdam Gorazda");
        jScrollPane3.setViewportView(jTextPane1);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout oprogramieframeLayout = new javax.swing.GroupLayout(oprogramieframe.getContentPane());
        oprogramieframe.getContentPane().setLayout(oprogramieframeLayout);
        oprogramieframeLayout.setHorizontalGroup(
            oprogramieframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, oprogramieframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        oprogramieframeLayout.setVerticalGroup(
            oprogramieframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oprogramieframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        kasujDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        kasujDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        kasujPole.setText("Podaj poprawna date.");
        kasujPole.addActionListener(formListener);

        kasujButton.setText("Kasuj");
        kasujButton.addActionListener(formListener);

        jLabel4.setText("Podaj date w formacie: yyyy-MM-dd");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(kasujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(kasujPole, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel4)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kasujPole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kasujButton)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout kasujDialogLayout = new javax.swing.GroupLayout(kasujDialog.getContentPane());
        kasujDialog.getContentPane().setLayout(kasujDialogLayout);
        kasujDialogLayout.setHorizontalGroup(
            kasujDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        kasujDialogLayout.setVerticalGroup(
            kasujDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GUI");
        setPreferredSize(new java.awt.Dimension(800, 740));
        addPropertyChangeListener(formListener);
        addWindowListener(formListener);

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ROK:");

        Miesiac.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Miesiac.setText(kalendarz.getMiesiac());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("MIESIĄC:");

        Rok.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        Rok.setText(kalendarz.getRok());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("LICZBA DNI:");

        Dni.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Dni.setText(kalendarz.getDni());

        jButton1.setText("<");
        jButton1.addActionListener(formListener);
        jSplitPane1.setLeftComponent(jButton1);

        jButton2.setText(">");
        jButton2.addActionListener(formListener);
        jSplitPane1.setRightComponent(jButton2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1)
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel3))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Miesiac)
                        .addComponent(Rok, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Rok, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(17, 17, 17)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Miesiac, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Dni, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap()))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DNI"));

        dni.setModel(new javax.swing.AbstractListModel()
            {
                public int getSize() { return kalendarz.getliczbaDni(); }
                public Object getElementAt(int i) { return kalendarz.getlistaDni()[i]; }
            });
            dni.addListSelectionListener(formListener);
            jScrollPane4.setViewportView(dni);

            warning.setForeground(new java.awt.Color(255, 0, 0));
            warning.setText("Nalezy wybrac dzien!");

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(warning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(warning, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(44, Short.MAX_VALUE))
            );

            jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dzwiek"));
            jPanel3.setToolTipText("");

            testujButton.setText("Test");
            testujButton.addActionListener(formListener);

            ustawPrzypButton.setText("Ustaw Przypomninie");
            ustawPrzypButton.addActionListener(formListener);

            zegarText.addActionListener(formListener);

            jLabel7.setText("CZAS BIEŻĄCY");

            jLabel8.setText("CZAS PRZYPOMNIENIA");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel8)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(zegarText)
                                .addComponent(ustawPrzypButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(nastawText)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(12, 12, 12)
                                            .addComponent(jLabel7))
                                        .addComponent(testujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(testujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(zegarText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jLabel8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(nastawText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(ustawPrzypButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32))
            );

            Zamknij.setText("Zamknij");
            Zamknij.addActionListener(formListener);

            jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("GODZINA"));

            godzina.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(godzina, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(godzina, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            Zdarzenia.setBorder(javax.swing.BorderFactory.createTitledBorder("Zdarzenia"));

            dodajZdarzenie.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            dodajZdarzenie.setText("DODAJ ZDARZENIE");
            dodajZdarzenie.addActionListener(formListener);

            wyswietl.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            wyswietl.setText("ZARZADZAJ");
            wyswietl.addActionListener(formListener);

            czysc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
            czysc.setForeground(new java.awt.Color(255, 0, 0));
            czysc.setText("CZYSC");
            czysc.addActionListener(formListener);

            kasujbutton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            kasujbutton.setText("KASUJ STARSZE");
            kasujbutton.addActionListener(formListener);

            javax.swing.GroupLayout ZdarzeniaLayout = new javax.swing.GroupLayout(Zdarzenia);
            Zdarzenia.setLayout(ZdarzeniaLayout);
            ZdarzeniaLayout.setHorizontalGroup(
                ZdarzeniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ZdarzeniaLayout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addGroup(ZdarzeniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kasujbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(czysc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(wyswietl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dodajZdarzenie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            ZdarzeniaLayout.setVerticalGroup(
                ZdarzeniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ZdarzeniaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(dodajZdarzenie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(wyswietl, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(kasujbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(czysc)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            nazwazdarzenia.setBorder(javax.swing.BorderFactory.createTitledBorder("Nazwa"));

            glownyPanel.setViewportView(nazwaZdarzenia);

            javax.swing.GroupLayout nazwazdarzeniaLayout = new javax.swing.GroupLayout(nazwazdarzenia);
            nazwazdarzenia.setLayout(nazwazdarzeniaLayout);
            nazwazdarzeniaLayout.setHorizontalGroup(
                nazwazdarzeniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(nazwazdarzeniaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(glownyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addContainerGap())
            );
            nazwazdarzeniaLayout.setVerticalGroup(
                nazwazdarzeniaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nazwazdarzeniaLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(glownyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            );

            minuty.setBorder(javax.swing.BorderFactory.createTitledBorder("Minuty"));

            minutySlider.setMaximum(60);
            minutySlider.setValue(30);

            jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

            org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, minutySlider, org.jdesktop.beansbinding.ELProperty.create("${value}"), jLabel6, org.jdesktop.beansbinding.BeanProperty.create("text"));
            bindingGroup.addBinding(binding);

            javax.swing.GroupLayout minutyLayout = new javax.swing.GroupLayout(minuty);
            minuty.setLayout(minutyLayout);
            minutyLayout.setHorizontalGroup(
                minutyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(minutyLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minutySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
                .addGroup(minutyLayout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(jLabel6)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            minutyLayout.setVerticalGroup(
                minutyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, minutyLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                    .addComponent(minutySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            miejscePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Miejsce"));

            javax.swing.GroupLayout miejscePanelLayout = new javax.swing.GroupLayout(miejscePanel);
            miejscePanel.setLayout(miejscePanelLayout);
            miejscePanelLayout.setHorizontalGroup(
                miejscePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(miejscePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(miejsceTextArea)
                    .addContainerGap())
            );
            miejscePanelLayout.setVerticalGroup(
                miejscePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(miejscePanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(miejsceTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jMenu4.setText("MENU");

            jMenuItem4.setText("O programie");
            jMenuItem4.addActionListener(formListener);
            jMenu4.add(jMenuItem4);

            jMenuItem2.setText("Zamknij");

            binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${dispose}"), jMenuItem2, org.jdesktop.beansbinding.BeanProperty.create("selected"));
            bindingGroup.addBinding(binding);

            jMenuItem2.addActionListener(formListener);
            jMenu4.add(jMenuItem2);

            jMenuBar1.add(jMenu4);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(Zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(minuty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nazwazdarzenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(miejscePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Zdarzenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(42, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(minuty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(66, 66, 66)
                                    .addComponent(nazwazdarzenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(miejscePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Zamknij, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(4, 4, 4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                            .addComponent(Zdarzenia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(55, Short.MAX_VALUE))
            );

            getAccessibleContext().setAccessibleDescription("");

            bindingGroup.bind();

            pack();
        }

        // Code for dispatching events from components to event handlers.

        private class FormListener implements java.awt.event.ActionListener, java.awt.event.WindowListener, java.beans.PropertyChangeListener, javax.swing.event.ListSelectionListener
        {
            FormListener() {}
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                if (evt.getSource() == jButton1)
                {
                    GUI.this.jButton1ActionPerformed(evt);
                }
                else if (evt.getSource() == jButton2)
                {
                    GUI.this.jButton2ActionPerformed(evt);
                }
                else if (evt.getSource() == testujButton)
                {
                    GUI.this.testujButtonActionPerformed(evt);
                }
                else if (evt.getSource() == ustawPrzypButton)
                {
                    GUI.this.ustawPrzypButtonActionPerformed(evt);
                }
                else if (evt.getSource() == zegarText)
                {
                    GUI.this.zegarTextActionPerformed(evt);
                }
                else if (evt.getSource() == Zamknij)
                {
                    GUI.this.ZamknijActionPerformed(evt);
                }
                else if (evt.getSource() == dodajZdarzenie)
                {
                    GUI.this.dodajZdarzenieActionPerformed(evt);
                }
                else if (evt.getSource() == wyswietl)
                {
                    GUI.this.wyswietlActionPerformed(evt);
                }
                else if (evt.getSource() == czysc)
                {
                    GUI.this.czyscActionPerformed(evt);
                }
                else if (evt.getSource() == kasujbutton)
                {
                    GUI.this.kasujbuttonActionPerformed(evt);
                }
                else if (evt.getSource() == jButton4)
                {
                    GUI.this.jButton4ActionPerformed(evt);
                }
                else if (evt.getSource() == jButton3)
                {
                    GUI.this.jButton3ActionPerformed(evt);
                }
                else if (evt.getSource() == serializujButton)
                {
                    GUI.this.serializujButtonActionPerformed(evt);
                }
                else if (evt.getSource() == deserializujButton)
                {
                    GUI.this.deserializujButtonActionPerformed(evt);
                }
                else if (evt.getSource() == zapiszCSVButton)
                {
                    GUI.this.zapiszCSVButtonActionPerformed(evt);
                }
                else if (evt.getSource() == wczytajCSVButton)
                {
                    GUI.this.wczytajCSVButtonActionPerformed(evt);
                }
                else if (evt.getSource() == takButton)
                {
                    GUI.this.takButtonActionPerformed(evt);
                }
                else if (evt.getSource() == nieButton)
                {
                    GUI.this.nieButtonActionPerformed(evt);
                }
                else if (evt.getSource() == jToggleButton1)
                {
                    GUI.this.jToggleButton1ActionPerformed(evt);
                }
                else if (evt.getSource() == kasujPole)
                {
                    GUI.this.kasujPoleActionPerformed(evt);
                }
                else if (evt.getSource() == kasujButton)
                {
                    GUI.this.kasujButtonActionPerformed(evt);
                }
                else if (evt.getSource() == jMenuItem4)
                {
                    GUI.this.jMenuItem4ActionPerformed(evt);
                }
                else if (evt.getSource() == jMenuItem2)
                {
                    GUI.this.jMenuItem2ActionPerformed(evt);
                }
            }

            public void windowActivated(java.awt.event.WindowEvent evt)
            {
            }

            public void windowClosed(java.awt.event.WindowEvent evt)
            {
                if (evt.getSource() == GUI.this)
                {
                    GUI.this.formWindowClosed(evt);
                }
            }

            public void windowClosing(java.awt.event.WindowEvent evt)
            {
            }

            public void windowDeactivated(java.awt.event.WindowEvent evt)
            {
            }

            public void windowDeiconified(java.awt.event.WindowEvent evt)
            {
            }

            public void windowIconified(java.awt.event.WindowEvent evt)
            {
            }

            public void windowOpened(java.awt.event.WindowEvent evt)
            {
            }

            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                if (evt.getSource() == GUI.this)
                {
                    GUI.this.formPropertyChange(evt);
                }
            }

            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                if (evt.getSource() == dni)
                {
                    GUI.this.dniValueChanged(evt);
                }
            }
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        kalendarz.poprzedniMiesiac();
        update();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        kalendarz.nastepnyMiesiac();
        update();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_formPropertyChange
    {//GEN-HEADEREND:event_formPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_formPropertyChange

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ZamknijActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ZamknijActionPerformed
    {//GEN-HEADEREND:event_ZamknijActionPerformed

        this.dispose();
    }//GEN-LAST:event_ZamknijActionPerformed

    private void testujButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_testujButtonActionPerformed
    {//GEN-HEADEREND:event_testujButtonActionPerformed

        new Dzwiek("01.wav", 1).odtworzDzwiek(1, true);
    }//GEN-LAST:event_testujButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton4ActionPerformed
    {//GEN-HEADEREND:event_jButton4ActionPerformed
        bazadanychframe.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void wyswietlActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_wyswietlActionPerformed
    {//GEN-HEADEREND:event_wyswietlActionPerformed
        zdarzenia.setModel(BdHibernate.getTableModel());
        //zdarzenia.setModel(Bd.getTableModel());
        bazadanychframe.setVisible(true);

    }//GEN-LAST:event_wyswietlActionPerformed

    private void dodajZdarzenieActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_dodajZdarzenieActionPerformed
    {//GEN-HEADEREND:event_dodajZdarzenieActionPerformed
        if (dni.getSelectedIndex() != -1)
        {
            new BdHibernate().dodajZdarzenie(kalendarz.getRok() + "-" + kalendarz.getIntMiesiac() + "-" + (dni.getSelectedIndex() + 1), (Integer) godzina.getValue(), (Integer) minutySlider.getValue(), nazwaZdarzenia.getText(), miejsceTextArea.getText(), 0);
            //Bd.dodajWpis(kalendarz.getRok() + "-" + kalendarz.getIntMiesiac() + "-" + (dni.getSelectedIndex() + 1), nazwaZdarzenia.getText(), (Integer) godzina.getValue());
        }

    }//GEN-LAST:event_dodajZdarzenieActionPerformed

    private void dniValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_dniValueChanged
    {//GEN-HEADEREND:event_dniValueChanged
        warning.setVisible(false);
    }//GEN-LAST:event_dniValueChanged

    private void czyscActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_czyscActionPerformed
    {//GEN-HEADEREND:event_czyscActionPerformed
        czyCzysc.setVisible(true);
    }//GEN-LAST:event_czyscActionPerformed

    private void nieButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_nieButtonActionPerformed
    {//GEN-HEADEREND:event_nieButtonActionPerformed
        czyCzysc.dispose();
    }//GEN-LAST:event_nieButtonActionPerformed

    private void takButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_takButtonActionPerformed
    {//GEN-HEADEREND:event_takButtonActionPerformed
        BdHibernate.czysc();
        czyCzysc.dispose();
    }//GEN-LAST:event_takButtonActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        oprogramieframe.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jToggleButton1ActionPerformed
    {//GEN-HEADEREND:event_jToggleButton1ActionPerformed
        oprogramieframe.dispose();
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void kasujPoleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kasujPoleActionPerformed
    {//GEN-HEADEREND:event_kasujPoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kasujPoleActionPerformed

    private void kasujButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kasujButtonActionPerformed
    {//GEN-HEADEREND:event_kasujButtonActionPerformed
        String str = kasujPole.getText();
        try
        {
            BdHibernate.usunStarsze(str);
            kasujDialog.dispose();
        } catch (ParseException e)
        {
            kasujPole.setText("Data musi miec dobry format!");
        }
    }//GEN-LAST:event_kasujButtonActionPerformed

    private void kasujbuttonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_kasujbuttonActionPerformed
    {//GEN-HEADEREND:event_kasujbuttonActionPerformed
        kasujDialog.setVisible(true);

    }//GEN-LAST:event_kasujbuttonActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton3ActionPerformed
    {//GEN-HEADEREND:event_jButton3ActionPerformed
        try
        {
            BdHibernate.usunZdarzenie((Integer) zdarzenia.getValueAt(zdarzenia.getSelectedRow(), 0));
            zdarzenia.setModel(BdHibernate.getTableModel());
        } catch (IndexOutOfBoundsException e)
        {

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void serializujButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_serializujButtonActionPerformed
    {//GEN-HEADEREND:event_serializujButtonActionPerformed
        BdHibernate.serializujXML();
    }//GEN-LAST:event_serializujButtonActionPerformed

    private void deserializujButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_deserializujButtonActionPerformed
    {//GEN-HEADEREND:event_deserializujButtonActionPerformed

        BdHibernate.deserializujXML();
        zdarzenia.setModel(BdHibernate.getTableModel());

    }//GEN-LAST:event_deserializujButtonActionPerformed

    private void zapiszCSVButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zapiszCSVButtonActionPerformed
    {//GEN-HEADEREND:event_zapiszCSVButtonActionPerformed
        BdHibernate.zapisCSV();

    }//GEN-LAST:event_zapiszCSVButtonActionPerformed

    private void wczytajCSVButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_wczytajCSVButtonActionPerformed
    {//GEN-HEADEREND:event_wczytajCSVButtonActionPerformed
        BdHibernate.czytajCSV();
        zdarzenia.setModel(BdHibernate.getTableModel());

    }//GEN-LAST:event_wczytajCSVButtonActionPerformed

    private void ustawPrzypButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_ustawPrzypButtonActionPerformed
    {//GEN-HEADEREND:event_ustawPrzypButtonActionPerformed
        kalendarz.przypomnienie.set(kalendarz.getCalendar().get(Calendar.YEAR), kalendarz.getCalendar().get(Calendar.MONTH), kalendarz.getCalendar().get(Calendar.DATE), (int) godzina.getValue(), minutySlider.getValue(), 00);
        nastawText.setText(kalendarz.getPrzypomnienie());
        kalendarz.flaga = true;
    }//GEN-LAST:event_ustawPrzypButtonActionPerformed

    private void zegarTextActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_zegarTextActionPerformed
    {//GEN-HEADEREND:event_zegarTextActionPerformed

    }//GEN-LAST:event_zegarTextActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        t.stop();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            @Override
            public void run()
            {
                new GUI().setVisible(true);

            }
        });

    }

    private Timer t;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dni;
    private javax.swing.JLabel Miesiac;
    private javax.swing.JLabel Rok;
    private javax.swing.JToggleButton Zamknij;
    private javax.swing.JPanel Zdarzenia;
    private javax.swing.JFrame bazadanychframe;
    private javax.swing.JDialog czyCzysc;
    private javax.swing.JButton czysc;
    private javax.swing.JButton deserializujButton;
    private javax.swing.JList dni;
    private javax.swing.JButton dodajZdarzenie;
    private javax.swing.JScrollPane glownyPanel;
    private javax.swing.JSpinner godzina;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton kasujButton;
    private javax.swing.JDialog kasujDialog;
    private javax.swing.JTextField kasujPole;
    private javax.swing.JButton kasujbutton;
    private javax.swing.JPanel miejscePanel;
    private javax.swing.JTextField miejsceTextArea;
    private javax.swing.JPanel minuty;
    private javax.swing.JSlider minutySlider;
    private javax.swing.JTextField nastawText;
    private javax.swing.JTextPane nazwaZdarzenia;
    private javax.swing.JPanel nazwazdarzenia;
    private javax.swing.JButton nieButton;
    private javax.swing.JFrame oprogramieframe;
    private javax.swing.JButton serializujButton;
    private javax.swing.JButton takButton;
    private javax.swing.JButton testujButton;
    private javax.swing.JButton ustawPrzypButton;
    private javax.swing.JLabel warning;
    private javax.swing.JButton wczytajCSVButton;
    private javax.swing.JButton wyswietl;
    private javax.swing.JButton zapiszCSVButton;
    private javax.swing.JTable zdarzenia;
    private static javax.swing.JTextField zegarText;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    private void update()
    {
        Miesiac.setText(kalendarz.getMiesiac());
        Rok.setText(kalendarz.getRok());
        Dni.setText(kalendarz.getDni());
        dni.updateUI();
    }

    /**
     * @return the kalendarz
     */
    public Kalendarz getKalendarz()
    {
        return kalendarz;
    }

    /**
     * @param kalendarz the kalendarz to set
     */
    public void setKalendarz(Kalendarz kalendarz)
    {
        this.kalendarz = kalendarz;
    }
}
