package com.mycompany.gui;
// Generated 2015-05-24 15:44:51 by Hibernate Tools 4.3.1

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Zdarzenie generated by hbm2java
 */
public class Zdarzenie implements java.io.Serializable
{

    private Integer idZdarzenie;
    private Date data;
    private Integer godzina;
    private Integer minuta;
    private String nazwa;
    private String miejsce;
    private Integer przypomnienie;

    public Zdarzenie()
    {
    }

    public Zdarzenie(Date data, Integer godzina, Integer minuta, String nazwa, String miejsce, Integer przypomnienie)
    {
        this.data = data;
        this.godzina = godzina;
        this.minuta = minuta;
        this.nazwa = nazwa;
        this.miejsce = miejsce;
        this.przypomnienie = przypomnienie;
    }

    public Zdarzenie(String data, String godzina, String minuta, String nazwa, String miejsce, String przypomnienie)
    {
        SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
        Date d = new Date();
        try
        {
            d = formatter.parse(data);
        } catch (ParseException ex)
        {
            Logger.getLogger(Zdarzenie.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.data = d;
        this.godzina = Integer.parseInt(godzina);
        this.minuta = Integer.parseInt(minuta);
        this.nazwa = nazwa;
        this.miejsce = miejsce;
        this.przypomnienie = Integer.parseInt(przypomnienie);
    }

    public Integer getIdZdarzenie()
    {
        return this.idZdarzenie;
    }

    public void setIdZdarzenie(Integer idZdarzenie)
    {
        this.idZdarzenie = idZdarzenie;
    }

    public Date getData()
    {
        return this.data;
    }

    public void setData(Date data)
    {
        this.data = data;
    }

    public Integer getGodzina()
    {
        return this.godzina;
    }

    public void setGodzina(Integer godzina)
    {
        this.godzina = godzina;
    }

    public Integer getMinuta()
    {
        return this.minuta;
    }

    public void setMinuta(Integer minuta)
    {
        this.minuta = minuta;
    }

    public String getNazwa()
    {
        return this.nazwa;
    }

    public void setNazwa(String nazwa)
    {
        this.nazwa = nazwa;
    }

    public String getMiejsce()
    {
        return this.miejsce;
    }

    public void setMiejsce(String miejsce)
    {
        this.miejsce = miejsce;
    }

    public Integer getPrzypomnienie()
    {
        return this.przypomnienie;
    }

    public void setPrzypomnienie(Integer przypomnienie)
    {
        this.przypomnienie = przypomnienie;
    }

}
